server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secretKey: wkoegfn23FFufwndEo04R0R9NO2URNIRPDM30E3IRRJMFDMiid3io3irdixPODDMOEOID3FNCLKKDMFNOSDCC

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: Authentication
            - name: Authorization
              args:
                roles: "ADMIN,SUPER_ADMIN"

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrderGatewayFilter
            - name: Authentication
            - name: Authorization
              args:
                roles: "ADMIN,SUPER_ADMIN"

        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**
          filters:
            - StripPrefix=2
            - name: Authentication
            - name: Authorization
              args:
                roles: "ADMIN,SUPER_ADMIN"
