apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  INVENTORY_DB_USER: cG9zdGdyZXM=
  INVENTORY_DB_PASSWORD: UG9zdGdyZXNAMTIz
  INVENTORY_DB_NAME: aW52ZW50b3J5TWljcm9zZXJ2aWNlREI=
  ORDER_DB_USER: cG9zdGdyZXM=
  ORDER_DB_PASSWORD: UG9zdGdyZXNAMTIz
  ORDER_DB_NAME: b3JkZXJNaWNyb3NlcnZpY2VEQg==
  SHIPPING_DB_USER: cG9zdGdyZXM=
  SHIPPING_DB_PASSWORD: UG9zdGdyZXNAMTIz
  SHIPPING_DB_NAME: c2hpcHBpbmdNaWNyb3NlcnZpY2VEQg==
