apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: lokesh2yss/ecommerce-order-service
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
         - name: SPRING_PROFILES_ACTIVE
           value: k8s
         - name: DB_USER
           value: "postgres"
         - name: DB_PASSWORD
           value: "Postgres@123"
         - name: DB_NAME
           value: "orderMicroserviceDB"
         - name: DB_SERVICE
           value: "order-db-service"
        ports:
        - containerPort: 9020

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 80
    targetPort: 9020

